### ISSUE TITLE
Generalize?

### ISSUE THREAD

**Issue by adamtopaz** [adamtopaz/comb_geom#9]
https://github.com/adamtopaz/comb_geom/blob/b0b15ad412387539336e34d6a3e582a3f222d36c/src/pregeom/basis.lean#L271

The following is also true, and more general. 
```lean
theorem basis_card_le_basis_card {B1 B2 : set T} (hb1 : is_basis B1) (hb2 : is_spanning B2)
  : cardinal.mk B1 ≤ cardinal.mk B2 := sorry
```

**Comment by ColterMac** [comment]
We know that a basis is a minimal spanning set, and hopefully lifting set inequality to cardinality inequality won't be too bad!

**Comment by adamtopaz** [comment]
Resolved!
